-- CREATE SCHEMA "loggings_schema";
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "loggings_schema"."logging" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"time" timestamp NOT NULL,
-- 	"source" text NOT NULL,
-- 	"note" text,
-- 	"json" json,
-- 	"message" text
-- );
-- --> statement-breakpoint
-- DROP TABLE "logs_schema"."logging";--> statement-breakpoint
-- DROP SCHEMA "logs_schema";
