-- ALTER TABLE "users_schema"."users" ALTER COLUMN "first_name" DROP DEFAULT;--> statement-breakpoint
-- ALTER TABLE "users_schema"."users" ALTER COLUMN "first_name" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "users_schema"."users" ALTER COLUMN "last_name" DROP DEFAULT;--> statement-breakpoint
-- ALTER TABLE "users_schema"."users" ALTER COLUMN "last_name" SET NOT NULL;